/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
      extend: {
        colors: {
          // Colores principales del logo CyborgTech
          'cyborg-primary': {
            50: 'var(--color-primary-50)',
            100: 'var(--color-primary-100)',
            200: 'var(--color-primary-200)',
            300: 'var(--color-primary-300)',
            400: 'var(--color-primary-400)',
            500: 'var(--color-primary-500)',
            600: 'var(--color-primary-600)',
            700: 'var(--color-primary-700)',
            800: 'var(--color-primary-800)',
            900: 'var(--color-primary-900)',
            950: 'var(--color-primary-950)',
          },
          'cyborg-secondary': {
            50: 'var(--color-secondary-50)',
            100: 'var(--color-secondary-100)',
            200: 'var(--color-secondary-200)',
            300: 'var(--color-secondary-300)',
            400: 'var(--color-secondary-400)',
            500: 'var(--color-secondary-500)',
            600: 'var(--color-secondary-600)',
            700: 'var(--color-secondary-700)',
            800: 'var(--color-secondary-800)',
            900: 'var(--color-secondary-900)',
            950: 'var(--color-secondary-950)',
          },
          'cyborg-accent': {
            50: 'var(--color-accent-50)',
            100: 'var(--color-accent-100)',
            200: 'var(--color-accent-200)',
            300: 'var(--color-accent-300)',
            400: 'var(--color-accent-400)',
            500: 'var(--color-accent-500)',
            600: 'var(--color-accent-600)',
            700: 'var(--color-accent-700)',
            800: 'var(--color-accent-800)',
            900: 'var(--color-accent-900)',
            950: 'var(--color-accent-950)',
          },
          'cyborg-dark': {
            50: 'var(--color-dark-50)',
            100: 'var(--color-dark-100)',
            200: 'var(--color-dark-200)',
            300: 'var(--color-dark-300)',
            400: 'var(--color-dark-400)',
            500: 'var(--color-dark-500)',
            600: 'var(--color-dark-600)',
            700: 'var(--color-dark-700)',
            800: 'var(--color-dark-800)',
            900: 'var(--color-dark-900)',
            950: 'var(--color-dark-950)',
          },
          // Sobrescribir los colores por defecto con nuestro sistema
          'primary': {
            50: 'var(--color-primary-50)',
            100: 'var(--color-primary-100)',
            200: 'var(--color-primary-200)',
            300: 'var(--color-primary-300)',
            400: 'var(--color-primary-400)',
            500: 'var(--color-primary-500)',
            600: 'var(--color-primary-600)',
            700: 'var(--color-primary-700)',
            800: 'var(--color-primary-800)',
            900: 'var(--color-primary-900)',
          },
          'secondary': {
            50: 'var(--color-secondary-50)',
            100: 'var(--color-secondary-100)',
            200: 'var(--color-secondary-200)',
            300: 'var(--color-secondary-300)',
            400: 'var(--color-secondary-400)',
            500: 'var(--color-secondary-500)',
            600: 'var(--color-secondary-600)',
            700: 'var(--color-secondary-700)',
            800: 'var(--color-secondary-800)',
            900: 'var(--color-secondary-900)',
          },
          'accent': {
            50: 'var(--color-accent-50)',
            100: 'var(--color-accent-100)',
            200: 'var(--color-accent-200)',
            300: 'var(--color-accent-300)',
            400: 'var(--color-accent-400)',
            500: 'var(--color-accent-500)',
            600: 'var(--color-accent-600)',
            700: 'var(--color-accent-700)',
            800: 'var(--color-accent-800)',
            900: 'var(--color-accent-900)',
          },
          // Actualizar azules existentes con nuestro sistema
          'blue': {
            50: 'var(--color-dark-50)',
            100: 'var(--color-dark-100)',
            200: 'var(--color-dark-200)',
            300: 'var(--color-dark-300)',
            400: 'var(--color-dark-400)',
            500: 'var(--color-dark-500)',
            600: 'var(--color-dark-600)',
            700: 'var(--color-dark-700)',
            800: 'var(--color-dark-800)',
            900: 'var(--color-dark-900)',
          },
          // Actualizar verdes con nuestro primary
          'green': {
            50: 'var(--color-primary-50)',
            100: 'var(--color-primary-100)',
            200: 'var(--color-primary-200)',
            300: 'var(--color-primary-300)',
            400: 'var(--color-primary-400)',
            500: 'var(--color-primary-500)',
            600: 'var(--color-primary-600)',
            700: 'var(--color-primary-700)',
            800: 'var(--color-primary-800)',
            900: 'var(--color-primary-900)',
          },
          // Actualizar amarillos con nuestro accent
          'yellow': {
            50: 'var(--color-accent-50)',
            100: 'var(--color-accent-100)',
            200: 'var(--color-accent-200)',
            300: 'var(--color-accent-300)',
            400: 'var(--color-accent-400)',
            500: 'var(--color-accent-500)',
            600: 'var(--color-accent-600)',
            700: 'var(--color-accent-700)',
            800: 'var(--color-accent-800)',
            900: 'var(--color-accent-900)',
          },
        },
        fontFamily: {
          'sans': 'var(--font-sans)',
          'mono': 'var(--font-mono)',
        },
        fontSize: {
          'xs': 'var(--text-xs)',
          'sm': 'var(--text-sm)',
          'base': 'var(--text-base)',
          'lg': 'var(--text-lg)',
          'xl': 'var(--text-xl)',
          '2xl': 'var(--text-2xl)',
          '3xl': 'var(--text-3xl)',
          '4xl': 'var(--text-4xl)',
          '5xl': 'var(--text-5xl)',
          '6xl': 'var(--text-6xl)',
        },
        spacing: {
          '1': 'var(--space-1)',
          '2': 'var(--space-2)',
          '3': 'var(--space-3)',
          '4': 'var(--space-4)',
          '5': 'var(--space-5)',
          '6': 'var(--space-6)',
          '8': 'var(--space-8)',
          '10': 'var(--space-10)',
          '12': 'var(--space-12)',
          '16': 'var(--space-16)',
          '20': 'var(--space-20)',
          '24': 'var(--space-24)',
        },
        borderRadius: {
          'sm': 'var(--radius-sm)',
          'DEFAULT': 'var(--radius-base)',
          'md': 'var(--radius-md)',
          'lg': 'var(--radius-lg)',
          'xl': 'var(--radius-xl)',
          '2xl': 'var(--radius-2xl)',
          '3xl': 'var(--radius-3xl)',
          'full': 'var(--radius-full)',
        },
        boxShadow: {
          'sm': 'var(--shadow-sm)',
          'DEFAULT': 'var(--shadow-base)',
          'md': 'var(--shadow-md)',
          'lg': 'var(--shadow-lg)',
          'xl': 'var(--shadow-xl)',
          '2xl': 'var(--shadow-2xl)',
        },
        transitionDuration: {
          'fast': '150ms',
          'base': '200ms',
          'slow': '300ms',
          'slower': '500ms',
        }
      },
    },
    plugins: [],
  };
  